#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Sun Nov 21 13:45:01 2010

import wx
from Main import Main

class Pyclops(wx.App):
    def OnInit(self):
        wx.InitAllImageHandlers()
        frame_1 = Main(None, -1, "")
        self.SetTopWindow(frame_1)
        frame_1.Show()
        return 1

# end of class Pyclops

if __name__ == "__main__":
    pyclops = Pyclops(0)
    pyclops.MainLoop()
